apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-test
spec:
  destination:
    namespace: wordpress-test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: wordpress
    repoURL: 'https://mcouliba.github.io/helm-charts'
    targetRevision: 0.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true