apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-prod
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/instance: wordpress-gitops-prod
spec:
  destination:
    namespace: wordpress-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: wordpress
    repoURL: 'https://mcouliba.github.io/helm-charts'
    targetRevision: 0.1.0
    helm:
      parameters:
        - name: deployment.mode
          value: PROD
        - name: image.repository
          value: image-registry.openshift-image-registry.svc:5000/wordpress-gitops/wordpress
        - name: image.tag
          value: '2.0'
        - name: database.host
          value: 'wordpress-mariadb.production-environment.svc:3306'
        - name: database.name
          value: 'd29yZHByZXNzZGI='
        - name: database.password
          value: 'd29yZHByZXNz'
        - name: database.root-password
          value: 'd29yZHByZXNzLWFkbWlu'
        - name: database.user
          value: 'd29yZHByZXNz'
