kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd
  namespace: wordpress-prod
  labels:
    app.kubernetes.io/instance: wordpress-gitops-prod
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: >-
      system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit