apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-gitops-main
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: wordpress-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ./openshift-gitops
    repoURL: 'https://github.com/mcouliba/wordpress-gitops'
    targetRevision: 'main'